# Install the development version of OmicsEV from GitHub:
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
install.packages("remotes")
BiocManager::install("theislab/kBET",update=FALSE,ask=FALSE)
require(devtools)
install_version("randomForest", version = "4.6-14", repos = "http://cran.r-project.org/",upgrade=FALSE)
install_version("missForest", version = "1.4", repos = "http://cran.r-project.org/",upgrade=FALSE)
install_version("rjson", version = "0.2.20", repos = "http://cran.r-project.org/",upgrade=FALSE)
install_version("GetoptLong", version = "1.0.4", repos = "http://cran.r-project.org/",upgrade=FALSE)
install_version("DiscriMiner", version = "0.1-29", repos = "http://cran.r-project.org/",upgrade=FALSE)
install_version("MALDIquant", version = "1.19.3", repos = "http://cran.r-project.org/",upgrade=FALSE)
install_version("locfit", version = "1.5-9.4", repos = "http://cran.r-project.org/",upgrade=FALSE)

BiocManager::install("wenbostar/metaX",update=FALSE,ask=FALSE)
BiocManager::install("bzhanglab/NetSAM",update=FALSE,ask=FALSE)
#BiocManager::install("AnalytixWare/ShinySky")
BiocManager::install("doMC",update=FALSE,ask=FALSE)
BiocManager::install("bzhanglab/OmicsEV",update=FALSE,ask=FALSE)
install_version("knitr", version = "1.31", repos = "http://cran.r-project.org/",upgrade=FALSE)
